version: "3.8"

services:
  langflow:
    image: langflowai/langflow:latest
    networks:
      - dokploy-network
    ports:
      - "7860"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.langflow.entrypoints=websecure"
      - "traefik.http.routers.langflow.tls.certResolver=letsencrypt"
      - "traefik.http.routers.langflow.rule=Host(`langflow.k2solucoessolar.com.br`)"
      - "traefik.http.services.langflow.loadbalancer.server.port=7860"
    deploy:
      resources:
        limits:
          memory: 600M
          cpus: "1"
        reservations:
          cpus: "0.5"
    environment:
      - LANGFLOW_DATABASE_URL=${LANGFLOW_DATABASE_URL}
      - LANGFLOW_SUPERUSER=aleiola
      - LANGFLOW_SUPERUSER_PASSWORD=aej25929
    volumes:
      - langflow-data:/app/langflow

volumes:
  langflow-data:

networks:
  dokploy-network:
    external: true
